kind: Deployment
apiVersion: apps/v1
metadata:
  name: deploy-java-stage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-stage
  template:
    metadata:
      labels:
        app: java-stage
    spec:
      containers: 
      - image: nguyenleminhquan/java-assignment:latest
        name: java-stage
        ports:
          - containerPort: 5000